#!/usr/bin/env python3

"""
 top level invocation script.
 
 A tool to convert a drum kit data base from one format to another one.
 
 For help run "genDrumkit -h"
 
 More documentation at https://github.com/peter-zenk/genDrumkit/wiki
"""

from gen_drum_kit.main import main

#------------------------------------------------------------------------------

program = main()

program.run() 

#------------------------------------------------------------------------------
# EOF
#------------------------------------------------------------------------------
